import React , { useState } from 'react';
import { setCookies } from 'cookies-next';
import Service from './api/Service';
import logo from '../public/logouniq.png';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Swal from 'sweetalert2';

export default function Home() {
  const [UserName, setUserName] = useState('');
  const [UserPass, setUserPass] = useState('');

  const inputUser =(event)=>{
    setUserName(event.target.value);
  }
  const inputPass =(event)=>{
    setUserPass(event.target.value);
  }

  const submitLogin = (event) => {
    event.preventDefault(); 


    let user = UserName;
    let pass = UserPass;




    try {
      if (user) {
        new Service().gettokenUser(user,pass).then(res => {

          console.log(res.data.status);

          if (res.data.status === '1') {
            setCookies('token', res.data.token, { path: '/', domain: '', maxAge: 4 * 60 * 60 });
            window.location.href='/components';

          } else {

            Swal.fire({
              position: 'center',
              icon: 'error',
              title: 'Username or Password ไม่ถูกต้อง',
              showConfirmButton: false,
              timer: 1500
            });
          }
          
        });
      } else {
        Swal.fire({
          position: 'center',
          icon: 'warning',
          title: 'กรุณากรอกรหัสพนักงาน',
          showConfirmButton: false,
          timer: 1500
        })
      }
    } catch (error) {

    }

    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Timesheet - Backend</title>
        <meta name="description" content="Generated by Unique" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className={styles.main}>
        <div className="row">
          <div className="col-12">     
            <div className="login-card">
              <div>
                  <div>
                      <a className="logo" href="index.html">
                          <Image  src={logo} alt="looginpage" width={120} height={150} />
                      </a>
                  </div>
                  <div className="login-main"> 
                      <form className="theme-form" onSubmit={submitLogin}>
                          <h4>Sign in to account</h4>
                          <p>Enter your username & password to login</p>
                          <div className="form-group">
                              <label className="col-form-label">Username</label>
                              <input className="form-control" type="text" required="" placeholder="Username" onChange={inputUser} />
                          </div>
                          <div className="form-group">
                              <label className="col-form-label">Password</label>
                              <input className="form-control" type="password" name="UserPassword" required="" placeholder="*********" onChange={inputPass} />
                          </div>
                          <div className="form-group mb-0">
                              <button className="btn btn-primary btn-block" type="submit">Sign in</button>
                          </div>
                      </form>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  )
}
